### ISSUE TITLE
Grammar highlighting and auto indent

### ISSUE THREAD

**Issue by wuqs-net** [Alhadis/language-turing#2]
![image](https://cloud.githubusercontent.com/assets/22854142/25257180/2d38faf0-2604-11e7-9eed-b85b74583c3b.png)
- When there is a `loop` inside a `loop`, grammar highlighting for `loop` does not work properly.
- When there is more than one `end loop`, the auto indent also goes wrong.

Reproduce:  
Copy code below into Atom and then auto-indent them.
```turing
loop
    put "hello"
    var i : int := 0
    loop
        put "world"
        i += 1
    end loop
end loop
```

**Comment by Alhadis** [comment]
@trifirew I'm very busy at the moment. A pull request is welcome, if you want to fix this yourself.

**Comment by wuqs-net** [comment]
@Alhadis I would like to. But I didn't find out where the problem is and how to fix it.
